name: Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow saat ada perubahan di branch `main`

permissions:
  contents: write  # Memberikan izin untuk menulis ke branch
  pages: write     # Memberikan izin untuk membuat deployment GitHub Pages
  id-token: write  # Memberikan izin untuk otentikasi OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run generate

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.output/public'  # Output Nuxt build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
